# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:

    filters:
      branches:
        only: 
          - develop
          - master

    docker:
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:

      - run:
          name: "Show npm and node versions"
          command: |
            node --version
            npm --version

      - checkout

      - restore_cache:
          keys:
          - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-packages-{{ .Branch }}
          - yarn-packages-

      # include devDependencies
      - run: yarn install --production=false

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

      - run: yarn docs:build

      - run: yarn docs:export

      - persist_to_workspace: 
          root: ~/repo
          paths:
            - .

  test:
    filters:
      branches:
        only: 
          - develop
          - master

    docker:
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Test
          command: yarn test

      - persist_to_workspace: 
          root: ~/repo
          paths:
            - .
  
  deploy:
    filters:
      branches:
        only: 
          - master

    docker:
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      # deploy docs
      - run: gh-pages -d docs/export

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      # only deploy tagged commits
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/