# This workflow is a workaround for ci.yml to bypass the github checks
#
# Ref: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: CI

on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:
    paths:
      # only runs this CI when changes are in 'docs/**' or 'examples/**'
      # the negate(!) is necessary, otherwise the CI runs when the changes are and are not in 'docs/**' or 'examples/**'
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths
      - 'docs/**'
      - '!docs/**'
      - 'examples/**'
      - '!examples/**'

permissions: {}

jobs:
  test-dev:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - run: 'echo "No build required"'
