name: Deploy preview

on:
  push:
    branches-ignore:
      # Renovate branches are always Pull Requests.
      # We don't need to run CI twice (push+pull_request)
      - 'renovate/**'
  pull_request:
    paths:
      - 'docs/**'

permissions: {}

jobs:
  main:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          # fetch all tags which are required for `yarn release:changelog`
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: 14
          cache: 'yarn' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: yarn install
        env:
          # Don't need playwright in this job
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - name: Add deploy previews to PR's comment
        run: yarn danger ci -d dangerfile.deploy-preview.ts -i deploy-preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
