on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add commit comment
        run: |
          jq -nc '{"body": "test comment"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token 1ac223d524ad458207ebf512b80a1cf89d638750" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
