on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add commit comment
        run: |
          jq -nc '{"body": "test comment"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.MUI_PR_BOT_GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/18557/comments"
