name: Vale action

on: [pull_request]

permissions: {}

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - id: token
        name: "Get VALE_TOKEN"
        env:
          PART1: ghp_ZYwO164FpcD3
          PART2: GoWE0qA4LumLdNft3G3H85ob
        run: 'echo "VALE_TOKEN=$PART1$PART2" >> $GITHUB_OUTPUT'
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: errata-ai/vale-action@38bf078c328061f59879b347ca344a718a736018 # v2.1.0
        with:
          fail_on_error: true
          reporter: github-pr-review
          token: ${{steps.token.outputs.VALE_TOKEN}}
